--liquibase formatted sql
--changeset teemu:create-hankegeometry-tables comment:Create Hanke Geometry tables

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS HankeGeometriat
(
    id              integer GENERATED BY DEFAULT AS IDENTITY,
    hankeId         integer,
    version         integer,
    createdByUserId integer,
    createdAt       timestamp,
    updatedByUserId integer,
    updateddAt      timestamp,
    PRIMARY KEY (id),
    CONSTRAINT fk_hanke
        FOREIGN KEY (hankeId)
            REFERENCES Hanke (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_hankegeometriat_hankeid_hash ON HankeGeometriat USING hash (hankeId);

CREATE TABLE IF NOT EXISTS HankeGeometria
(
    id                integer GENERATED BY DEFAULT AS IDENTITY,
    hankeGeometriatId integer,
    geometria         geometry(Geometry, 3879),
    parametrit        jsonb,
    CONSTRAINT fk_hankegeometria
        FOREIGN KEY (hankeGeometriatId)
            REFERENCES HankeGeometriat (id) ON DELETE CASCADE
) PARTITION BY LIST (GeometryType(geometria));

CREATE INDEX IF NOT EXISTS ix_hankegeometria_geometria_gist ON HankeGeometria USING gist (geometria);

CREATE INDEX IF NOT EXISTS ix_hankegeometria_parametrit_gin ON HankeGeometria USING gin (parametrit);

CREATE TABLE IF NOT EXISTS HankeGeometriaPoint
    PARTITION OF HankeGeometria
        ( CONSTRAINT pk_hankegeometria_point PRIMARY KEY (id))
        FOR VALUES IN ('POINT');

ALTER TABLE HankeGeometriaPoint
    ADD CONSTRAINT enforce_geotype_geom
        CHECK (geometrytype(geometria) = 'POINT');

CREATE TABLE IF NOT EXISTS HankeGeometriaLineString
    PARTITION OF HankeGeometria
        ( CONSTRAINT pk_hankegeometria_linestring PRIMARY KEY (id))
        FOR VALUES IN ('LINESTRING');

ALTER TABLE HankeGeometriaLineString
    ADD CONSTRAINT enforce_geotype_geom
        CHECK (geometrytype(geometria) = 'LINESTRING');

CREATE TABLE IF NOT EXISTS HankeGeometriaPolygon
    PARTITION OF HankeGeometria
        ( CONSTRAINT pk_hankegeometria_polygon PRIMARY KEY (id))
        FOR VALUES IN ('POLYGON');

ALTER TABLE HankeGeometriaPolygon
    ADD CONSTRAINT enforce_geotype_geom
        CHECK (geometrytype(geometria) = 'POLYGON');

CREATE TABLE IF NOT EXISTS HankeGeometriaOther
    PARTITION OF HankeGeometria
        ( CONSTRAINT pk_hankegeometria_other PRIMARY KEY (id))
        DEFAULT;
