version: "3"
volumes:
  haitaton_gis_prepare:
    external: true
  haitaton_gis_db:
    external: true
services:
  gis-db:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: haitaton-gis-prepare-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes:
      - haitaton_gis_db:/var/lib/postgresql/data
  gis-fetch:
    build:
      context: .
      dockerfile: fetch/Dockerfile.fetch
    container_name: haitaton-gis-fetch
    volumes:
      - haitaton_gis_prepare:/haitaton-gis
      - ./haitaton-downloads:/downloads

  gis-process:
    build:
      context: .
      dockerfile: fetch/Dockerfile.process
    container_name: haitaton-gis-process
    volumes:
      - haitaton_gis_prepare:/haitaton-gis
      - ./haitaton-downloads:/downloads
  
  # docker volume create --name haitaton_gis_prepare
  # docker volume create --name haitaton_gis_db
  # docker volume rm haitaton_gis_prepare
  # docker volume rm haitaton_gis_db
