#!/bin/bash
set -e

PGPASSWORD=${POSTGRES_PASSWORD} psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -h localhost <<-EOSQL
    CREATE DATABASE ${HAITATON_DB};
    CREATE USER ${HAITATON_USER} WITH PASSWORD '${HAITATON_USER_PW}';
    GRANT ALL PRIVILEGES ON DATABASE ${HAITATON_DB} TO ${HAITATON_USER};
    ALTER DATABASE ${HAITATON_DB} OWNER TO ${HAITATON_USER};
EOSQL