hypersistence.utils.json.serializer=fi.hel.haitaton.hanke.configuration.ObjectMapperCloningJsonSerializerSupplier
hypersistence.utils.jackson.object.mapper=fi.hel.haitaton.hanke.configuration.GeoJsonAwareObjectMapperSupplier
