# File: haitaton-backend/azure-pipelines.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - NON_EXISTING_FOR_NOW
  paths:
    exclude:
    - README.md

# no PR triggers
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: haitaton-hanke-service-pipelines
    type: git
    # project/repository
    name: haitaton/haitaton-hanke-service-pipelines

extends:
  template: azure-pipelines.yml@haitaton-hanke-service-pipelines
