TRUNCATE TABLE
    application_attachment,
    applications,
    audit_logs,
    geometriat,
    hakemusyhteyshenkilo,
    hakemusyhteystieto,
    hanke,
    hanke_attachment,
    hankekayttaja,
    hankealue,
    hankegeometria,
    hanketyomaatyyppi,
    hankeyhteyshenkilo,
    hankeyhteystieto,
    int_lock,
    kayttajakutsu,
    paatos,
    permissions,
    tormaystarkastelutulos,
    hankkeen_haittojenhallintasuunnitelma;
UPDATE allu_status SET history_last_updated = '2017-01-01T00:00:00Z';
