FROM gradle:jdk11-openj9 as builder
USER root
ADD . /builder
WORKDIR /builder
RUN gradle build --no-daemon

FROM openjdk:11
WORKDIR /app
EXPOSE 8080 8081
COPY --from=builder /builder/build/libs/builder-0.0.1-SNAPSHOT.jar /app/haitaton.jar
CMD ["java", "-jar", "haitaton.jar" ]