# Stage 1: Build application
FROM registry.access.redhat.com/ubi9/openjdk-17 AS build

USER root

# Set the working directory, copy gradle and source code
WORKDIR /app
COPY gradlew settings.gradle.kts ./
COPY gradle/ ./gradle/
COPY services/hanke-service/build.gradle.kts ./services/hanke-service/
COPY services/hanke-service/src ./services/hanke-service/src

# Build
RUN ./gradlew clean :services:hanke-service:assemble --stacktrace

# Stage 2: Create runtime image
FROM registry.access.redhat.com/ubi9/openjdk-17-runtime
VOLUME /tmp
WORKDIR /app
COPY --from=build /app/services/hanke-service/build/libs/hanke-service*SNAPSHOT.jar hanke-service.jar
EXPOSE 8080 8081
CMD [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/urandom -jar hanke-service.jar" ]
