FROM public.ecr.aws/docker/library/eclipse-temurin:17 as build
WORKDIR /workspace/app

COPY gradlew settings.gradle.kts ./
COPY gradle/ ./gradle/
COPY services/hanke-service/build.gradle.kts ./services/hanke-service/
COPY services/hanke-service/src/main ./services/hanke-service/src/main

RUN --mount=type=cache,target=/root/.gradle ./gradlew --no-daemon :services:hanke-service:assemble
RUN mkdir -p services/hanke-service/build/dependency && \
    (cd services/hanke-service/build/dependency; jar -xf ../libs/*SNAPSHOT.jar)

FROM public.ecr.aws/docker/library/eclipse-temurin:17
VOLUME /tmp

ARG DEPENDENCY=/workspace/app/services/hanke-service/build/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
COPY scripts/wait-for-it.sh ./


ENTRYPOINT ["./wait-for-it.sh", "db:5432", "--timeout=50", "--strict", "--", "java", "-cp", "app:app/lib/*", "fi.hel.haitaton.hanke.ApplicationKt"]
