name: hanke-service-dev

env:
  PATH: 'services/hanke-service'
  GRADLE_MODULE: 'services:hanke-service'
  ARTIFACT: 'haitaton-hanke-service'

on:
  push:
    branches:
      - 'dev'
    paths:
      - "$PATH/**"

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew :GRADLE_MODULE:build
      - name: Upload application jar file for Docker build job
        uses: actions/upload-artifact@v2
        with:
          name: $ARTIFACT-jar
          path: ./$PATH/build/libs/$ARTIFACT-*.jar
          retention-days: 1
  docker_build_and_push:
    name: Build and push Docker image to GitHub container registry
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $PATH
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Download application jar file
        uses: actions/download-artifact@v2
        with:
          name: $ARTIFACT-jar
      -
        name: List files after checkout
        shell: bash
        run: |
          ls -ltra
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to OpenShift Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHSA_USERNAME }}
          password: ${{ secrets.RHSA_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_OWNER }}
          password: ${{ secrets.CR_PAT }}
      -
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/city-of-helsinki/haitaton/$ARTIFACT:latest
            ghcr.io/city-of-helsinki/haitaton/$ARTIFACT:dev
